"""add salary structure assignment table

Revision ID: 0e6781b1eab0
Revises: c95f1ed126f7
Create Date: 2024-12-13 23:33:59.555414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e6781b1eab0'
down_revision = 'c95f1ed126f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_structure_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('salary_structure_id', sa.Integer(), nullable=False, comment='工资结构ID'),
    sa.Column('employee_id', sa.Integer(), nullable=True, comment='员工ID'),
    sa.Column('is_default', sa.Boolean(), nullable=True, comment='是否为默认工资结构'),
    sa.Column('effective_date', sa.Date(), nullable=False, comment='生效日期'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['salary_structure_id'], ['salary_structures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salary_structure_assignments')
    # ### end Alembic commands ###
