"""Add login attempt limit fields to User model in user.py

Revision ID: 21649012f0b7
Revises: ea89718562d7
Create Date: 2024-12-12 16:45:49.751433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21649012f0b7'
down_revision = 'ea89718562d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login_attempts', sa.Integer(), nullable=True, comment='登录失败尝试次数'))
    op.add_column('users', sa.Column('last_failed_login', sa.DateTime(), nullable=True, comment='最后一次登录失败时间'))
    op.add_column('users', sa.Column('account_locked_until', sa.DateTime(), nullable=True, comment='账户锁定截止时间'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'account_locked_until')
    op.drop_column('users', 'last_failed_login')
    op.drop_column('users', 'login_attempts')
    # ### end Alembic commands ###
