"""Add department_id to salary structure assignments

Revision ID: 3859c03adcde
Revises: 0e6781b1eab0
Create Date: 2024-12-14 23:41:34.578677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3859c03adcde'
down_revision = '0e6781b1eab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salary_structure_assignments', sa.Column('department_id', sa.Integer(), nullable=True, comment='部门ID'))
    op.create_foreign_key(None, 'salary_structure_assignments', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'salary_structure_assignments', type_='foreignkey')
    op.drop_column('salary_structure_assignments', 'department_id')
    # ### end Alembic commands ###
