"""add employees relationship to department

Revision ID: 673adb067a61
Revises: 4354786b2fe2
Create Date: 2024-12-09 23:11:28.694789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '673adb067a61'
down_revision = '4354786b2fe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
