"""initial_migration_with_all_tables

Revision ID: 8264af1f97fb
Revises: 
Create Date: 2024-12-17 16:08:43.474733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8264af1f97fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='规则名称'),
    sa.Column('work_start_time', sa.Time(), nullable=False, comment='上班时间'),
    sa.Column('work_end_time', sa.Time(), nullable=False, comment='下班时间'),
    sa.Column('late_threshold', sa.Integer(), nullable=True, comment='迟到阈值(分钟)'),
    sa.Column('early_leave_threshold', sa.Integer(), nullable=True, comment='早退阈值(分钟)'),
    sa.Column('overtime_minimum', sa.Integer(), nullable=True, comment='最小加班时长(分钟)'),
    sa.Column('is_default', sa.Boolean(), nullable=True, comment='是否为默认规则'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='规则说明'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], name='fk_department_manager', use_alter=True),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], name='fk_department_parent', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statutory_holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='节假日名称'),
    sa.Column('date', sa.Date(), nullable=False, comment='节假日日期'),
    sa.Column('holiday_type', sa.String(length=20), nullable=False, comment='类型(holiday:节假日/workday:调休工作日)'),
    sa.Column('year', sa.Integer(), nullable=False, comment='年份'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='描述'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False, comment='用户名'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='密码'),
    sa.Column('email', sa.String(length=120), nullable=False, comment='邮箱'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='角色(admin/manager/employee)'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('reset_code', sa.String(length=6), nullable=True, comment='重置密码验证码'),
    sa.Column('reset_code_expires', sa.DateTime(), nullable=True, comment='重置码过期时间'),
    sa.Column('login_attempts', sa.Integer(), nullable=True, comment='登录失败尝试次数'),
    sa.Column('last_failed_login', sa.DateTime(), nullable=True, comment='最后一次登录失败时间'),
    sa.Column('account_locked_until', sa.DateTime(), nullable=True, comment='账户锁定截止时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name='fk_position_department'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('education', sa.String(length=50), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('id_card', sa.String(length=18), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('resignation_date', sa.Date(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('employment_status', sa.String(length=20), nullable=False),
    sa.Column('employee_type', sa.String(length=20), nullable=False),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name='fk_employee_department'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name='fk_employee_position'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_employee_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_table('attendances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False, comment='员工ID'),
    sa.Column('date', sa.Date(), nullable=False, comment='考勤日期'),
    sa.Column('check_in', sa.DateTime(), nullable=True, comment='上班打卡时间'),
    sa.Column('check_out', sa.DateTime(), nullable=True, comment='下班打卡时间'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='考勤状态(normal/late/early/absent)'),
    sa.Column('remark', sa.String(length=200), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('education_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('school', sa.String(length=100), nullable=False),
    sa.Column('major', sa.String(length=100), nullable=True),
    sa.Column('degree', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intern_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('planned_end_date', sa.Date(), nullable=True),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('mentor_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name='fk_intern_department'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='fk_intern_employee'),
    sa.ForeignKeyConstraint(['mentor_id'], ['employees.id'], name='fk_intern_mentor'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name='fk_intern_position'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leaves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False, comment='员工ID'),
    sa.Column('leave_type', sa.String(length=20), nullable=False, comment='请假类型(sick/annual/personal/other)'),
    sa.Column('start_date', sa.DateTime(), nullable=False, comment='开始时间'),
    sa.Column('end_date', sa.DateTime(), nullable=False, comment='结束时间'),
    sa.Column('reason', sa.String(length=200), nullable=True, comment='请假原因'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态(pending/approved/rejected)'),
    sa.Column('approved_by', sa.Integer(), nullable=True, comment='审批人ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('overtimes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False, comment='员工ID'),
    sa.Column('start_time', sa.DateTime(), nullable=False, comment='开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=False, comment='结束时间'),
    sa.Column('reason', sa.String(length=200), nullable=True, comment='加班原因'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态(pending/approved/rejected)'),
    sa.Column('approved_by', sa.Integer(), nullable=True, comment='审批人ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position_change_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('old_department_id', sa.Integer(), nullable=True),
    sa.Column('new_department_id', sa.Integer(), nullable=False),
    sa.Column('old_position_id', sa.Integer(), nullable=True),
    sa.Column('new_position_id', sa.Integer(), nullable=False),
    sa.Column('change_date', sa.Date(), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['new_department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['new_position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['old_department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['old_position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salary_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False, comment='员工ID'),
    sa.Column('year', sa.Integer(), nullable=False, comment='年份'),
    sa.Column('month', sa.Integer(), nullable=False, comment='月份'),
    sa.Column('basic_salary', sa.Numeric(precision=10, scale=2), nullable=False, comment='基本工资'),
    sa.Column('allowances', sa.Numeric(precision=10, scale=2), nullable=True, comment='补贴总额'),
    sa.Column('overtime_pay', sa.Numeric(precision=10, scale=2), nullable=True, comment='加班费'),
    sa.Column('bonus', sa.Numeric(precision=10, scale=2), nullable=True, comment='奖金'),
    sa.Column('deductions', sa.Numeric(precision=10, scale=2), nullable=True, comment='扣除项(请假等)'),
    sa.Column('gross_salary', sa.Numeric(precision=10, scale=2), nullable=False, comment='应发总额'),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=True, comment='个人所得税'),
    sa.Column('net_salary', sa.Numeric(precision=10, scale=2), nullable=False, comment='实发工资'),
    sa.Column('payment_status', sa.String(length=20), nullable=True, comment='发放状态(pending/paid)'),
    sa.Column('payment_date', sa.DateTime(), nullable=True, comment='发放日期'),
    sa.Column('remark', sa.String(length=1000), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salary_structures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='薪资结构名称'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='描述'),
    sa.Column('basic_salary', sa.Numeric(precision=10, scale=2), nullable=False, comment='基本工资'),
    sa.Column('housing_allowance', sa.Numeric(precision=10, scale=2), nullable=True, comment='住房补贴'),
    sa.Column('transport_allowance', sa.Numeric(precision=10, scale=2), nullable=True, comment='交通补贴'),
    sa.Column('meal_allowance', sa.Numeric(precision=10, scale=2), nullable=True, comment='餐饮补贴'),
    sa.Column('effective_date', sa.Date(), nullable=False, comment='生效日期'),
    sa.Column('is_default', sa.Boolean(), nullable=True, comment='是否为默认薪资结构'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活'),
    sa.Column('employee_id', sa.Integer(), nullable=True, comment='员工ID，如果为空则为通用薪资结构'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('work_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intern_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intern_status_id', sa.Integer(), nullable=False),
    sa.Column('evaluation_date', sa.Date(), nullable=False),
    sa.Column('evaluation_type', sa.String(length=20), nullable=False),
    sa.Column('work_performance', sa.Integer(), nullable=False),
    sa.Column('learning_ability', sa.Integer(), nullable=False),
    sa.Column('communication_skill', sa.Integer(), nullable=False),
    sa.Column('professional_skill', sa.Integer(), nullable=False),
    sa.Column('attendance', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('evaluation_content', sa.Text(), nullable=True),
    sa.Column('improvement_suggestions', sa.Text(), nullable=True),
    sa.Column('conversion_recommended', sa.Boolean(), nullable=True),
    sa.Column('recommended_position_id', sa.Integer(), nullable=True),
    sa.Column('recommended_salary', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('conversion_comments', sa.Text(), nullable=True),
    sa.Column('evaluator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evaluator_id'], ['employees.id'], name='fk_evaluation_evaluator'),
    sa.ForeignKeyConstraint(['intern_status_id'], ['intern_status.id'], name='fk_evaluation_status'),
    sa.ForeignKeyConstraint(['recommended_position_id'], ['positions.id'], name='fk_evaluation_position'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salary_structure_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('salary_structure_id', sa.Integer(), nullable=False, comment='工资结构ID'),
    sa.Column('employee_id', sa.Integer(), nullable=True, comment='员工ID'),
    sa.Column('department_id', sa.Integer(), nullable=True, comment='部门ID'),
    sa.Column('is_default', sa.Boolean(), nullable=True, comment='是否为默认工资结构'),
    sa.Column('effective_date', sa.Date(), nullable=False, comment='生效日期'),
    sa.Column('expiry_date', sa.Date(), nullable=True, comment='失效日期'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['salary_structure_id'], ['salary_structures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salary_structure_assignments')
    op.drop_table('intern_evaluations')
    op.drop_table('work_history')
    op.drop_table('salary_structures')
    op.drop_table('salary_records')
    op.drop_table('position_change_history')
    op.drop_table('overtimes')
    op.drop_table('leaves')
    op.drop_table('intern_status')
    op.drop_table('education_history')
    op.drop_table('contract_attachments')
    op.drop_table('attendances')
    op.drop_table('employees')
    op.drop_table('positions')
    op.drop_table('users')
    op.drop_table('statutory_holidays')
    op.drop_table('departments')
    op.drop_table('attendance_rules')
    # ### end Alembic commands ###
