"""add reset password fields

Revision ID: 87de6bba46f6
Revises: 673adb067a61
Create Date: 2024-12-12 10:26:33.111588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87de6bba46f6'
down_revision = '673adb067a61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_code', sa.String(length=6), nullable=True, comment='重置密码验证码'))
    op.add_column('users', sa.Column('reset_code_expires', sa.DateTime(), nullable=True, comment='重置码过期时间'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_code_expires')
    op.drop_column('users', 'reset_code')
    # ### end Alembic commands ###
