"""add_employee_type_field

Revision ID: 9b253d5bb170
Revises: c2e271686119
Create Date: 2024-12-16 14:12:06.271695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b253d5bb170'
down_revision = 'c2e271686119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intern_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('planned_end_date', sa.Date(), nullable=True),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('mentor_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name='fk_intern_department'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='fk_intern_employee'),
    sa.ForeignKeyConstraint(['mentor_id'], ['employees.id'], name='fk_intern_mentor'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name='fk_intern_position'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intern_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intern_status_id', sa.Integer(), nullable=False),
    sa.Column('evaluation_date', sa.Date(), nullable=False),
    sa.Column('evaluation_type', sa.String(length=20), nullable=False),
    sa.Column('work_performance', sa.Integer(), nullable=False),
    sa.Column('learning_ability', sa.Integer(), nullable=False),
    sa.Column('communication_skill', sa.Integer(), nullable=False),
    sa.Column('professional_skill', sa.Integer(), nullable=False),
    sa.Column('attendance', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('evaluation_content', sa.Text(), nullable=True),
    sa.Column('improvement_suggestions', sa.Text(), nullable=True),
    sa.Column('conversion_recommended', sa.Boolean(), nullable=True),
    sa.Column('recommended_position_id', sa.Integer(), nullable=True),
    sa.Column('recommended_salary', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('conversion_comments', sa.Text(), nullable=True),
    sa.Column('evaluator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evaluator_id'], ['employees.id'], name='fk_evaluation_evaluator'),
    sa.ForeignKeyConstraint(['intern_status_id'], ['intern_status.id'], name='fk_evaluation_status'),
    sa.ForeignKeyConstraint(['recommended_position_id'], ['positions.id'], name='fk_evaluation_position'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('employees', sa.Column('employee_type', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'employee_type')
    op.drop_table('intern_evaluations')
    op.drop_table('intern_status')
    # ### end Alembic commands ###
