"""Add gross_salary column to salary_records table

Revision ID: c2e271686119
Revises: 9367a1b6cafc
Create Date: 2024-12-15 21:58:43.749093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2e271686119'
down_revision = '9367a1b6cafc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salary_records', sa.Column('gross_salary', sa.Numeric(precision=10, scale=2), nullable=False, comment='应发总额'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salary_records', 'gross_salary')
    # ### end Alembic commands ###
