"""add_is_default_and_employee_id_to_salary_structure

Revision ID: c95f1ed126f7
Revises: fcbedd8f4f75
Create Date: 2024-12-13 12:50:47.530445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c95f1ed126f7'
down_revision = 'fcbedd8f4f75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salary_structures', sa.Column('is_default', sa.Boolean(), nullable=True, comment='是否为默认薪资结构'))
    op.add_column('salary_structures', sa.Column('employee_id', sa.Integer(), nullable=True, comment='员工ID，如果为空则为通用薪资结构'))
    op.create_foreign_key(None, 'salary_structures', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'salary_structures', type_='foreignkey')
    op.drop_column('salary_structures', 'employee_id')
    op.drop_column('salary_structures', 'is_default')
    # ### end Alembic commands ###
