"""Add login attempt limit fields to User model

Revision ID: ea89718562d7
Revises: 87de6bba46f6
Create Date: 2024-12-12 16:42:05.828470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea89718562d7'
down_revision = '87de6bba46f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
