"""Update_salary_structure_model

Revision ID: fcbedd8f4f75
Revises: 21649012f0b7
Create Date: 2024-12-13 11:33:06.765825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fcbedd8f4f75'
down_revision = '21649012f0b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salary_structures', sa.Column('name', sa.String(length=100), nullable=False, comment='薪资结构名称'))
    op.add_column('salary_structures', sa.Column('description', sa.String(length=200), nullable=True, comment='描述'))
    op.create_unique_constraint(None, 'salary_structures', ['name'])
    op.drop_constraint('salary_structures_ibfk_1', 'salary_structures', type_='foreignkey')
    op.drop_column('salary_structures', 'employee_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salary_structures', sa.Column('employee_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='员工ID'))
    op.create_foreign_key('salary_structures_ibfk_1', 'salary_structures', 'employees', ['employee_id'], ['id'])
    op.drop_constraint(None, 'salary_structures', type_='unique')
    op.drop_column('salary_structures', 'description')
    op.drop_column('salary_structures', 'name')
    # ### end Alembic commands ###
